const multer = require("multer");
const express = require("express");
const router = express.Router();
const { userAuthMiddleware } = require("../../middleware/auth.middleware");
const upload= require("../../middleware/file.middleware")
const {
  generateResumePDFUsingReportController,
  generateResumeController,
  getUserResumesController,
  getResumeByIdController,
  downloadResumeController,
} = require("./resume.controller");

/**
 * @route   GET /api/resume/:resumeId/download
 * @desc    Download the saved PDF for a generated resume directly
 * @access  Public (so it can be hit directly via link)
 */
router.get("/:resumeId/download", downloadResumeController);

/**
 * @route   GET /api/resume/
 * @desc    List all resumes generated by the logged-in user (no HTML, just metadata)
 * @access  Private
 */
router.get("/", userAuthMiddleware, getUserResumesController);

/**
 * @route   GET /api/resume/generate/:interviewId
 * @desc    Generate a new AI-improved single-page resume PDF from an interview
 *          report, persist to DB, and stream the PDF back to the client.
 * @access  Private
 *
 * NOTE: This route MUST be declared before `/:resumeId` so Express doesn't
 *       mistake the literal "generate" segment for a MongoDB ObjectId.
 */
router.get(
  "/generate/:interviewId",
  userAuthMiddleware,
  generateResumePDFUsingReportController
);

/**
 * @route   GET /api/resume/generate/
 * @desc    Generate a new AI-improved single-page resume PDF from given user info
 *
 * @access  public
 *
 * NOTE: This route MUST be declared before `/:resumeId` so Express doesn't
 *       mistake the literal "generate" segment for a MongoDB ObjectId.
 */
router.post(
  "/generate/", upload.single("resume"),
   generateResumeController
)

/**
 * @route   GET /api/resume/:resumeId
 * @desc    Fetch the full HTML content + scores of a previously generated resume
 * @access  Private
 */
router.get("/:resumeId", userAuthMiddleware, getResumeByIdController);

module.exports = router;
